version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://ng-univ-lambda-template --recursive
      - aws s3 sync ./dist/app/browser s3://ng-univ-lambda-template/_angular
      - npm run deploy:dev
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
