version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build --base-href=/dev/
  post_build:
    commands:
      - npm run deploy:dev
